Repository formulajs/formulajs, pull requests merged in 2022-12, with the labels that each got.

#121 MATCH should work with mixed types lookup_array
  package-lock.json
  src/lookup-reference.js
  test/lookup-reference.js
Labels: bug

#124 Empty value handling in NUMBERVALUE and VALUE
  src/text.js
  test/text.js
Labels: bug

#127 Fix NUMBERVALUE with number input
  src/text.js
  test/text.js
Labels: bug

#128 MATCH with single value lookup_array
  package.json
  src/lookup-reference.js
  src/utils/common.js
  test/lookup-reference.js
  test/utils/common.js
Labels: bug

#129 Flatten inconsistency with Array arguments
  package-lock.json
  package.json
  src/statistical.js
  src/utils/common.js
  test/lookup-reference.js
  test/utils/common.js
Labels: bug, enhancement

#130 Implement FIXED, TEXT & DOLLAR functions
  src/text.js
  test/text.js
Labels: enhancement

#132 Replace `should` with `chai`
  package-lock.json
  package.json
  test/database.js
  test/date-time.js
  test/engineering.js
  test/financial.js
  test/information.js
  test/logical.js
  test/lookup-reference.js
  test/math-trig.js
  test/miscellaneous.js
  test/statistical.js
  test/text.js
  test/utils/common.js
  test/utils/criteria-eval.js
Labels: question
